development:
  adapter: postgresql
  encoding: unicode
  database: actioncable-react_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: actioncable-react_test
  pool: 5
  username: postgres
  password:
